### ISSUE TITLE
Code Coverage Failure

### ISSUE THREAD

**Issue by jitenderpadda** [launchdarkly/apex-server-sdk#9]
**Describe the bug**
Getting code coverage error on the following classes and hence unable to deploy to higher environments. Am I missing something here? I used version 1.1.0 -

- Your code coverage is 70%. You need at least 75% coverage to complete this deployment.
LD_Evaluator
- Your code coverage is 60%. You need at least 75% coverage to complete this deployment.
LD_EventREST
- Your code coverage is 54%. You need at least 75% coverage to complete this deployment.
LD_LDConfig
- Your code coverage is 47%. You need at least 75% coverage to complete this deployment.
LD_LDClient
- Your code coverage is 62%. You need at least 75% coverage to complete this deployment.
LD_LDValue
- Your code coverage is 0%. You need at least 75% coverage to complete this deployment.
LD_StoreREST
- Your code coverage is 66%. You need at least 75% coverage to complete this deployment.
LD_VersionedData

![image](https://user-images.githubusercontent.com/10905262/153538892-1749d974-ed97-41cf-9040-65c0633369aa.png)

Just deployed original SDK 1.1.0 and ran tests - 

![image](https://user-images.githubusercontent.com/10905262/153544466-1fb33737-cb30-4a1e-bd75-97cd8a615167.png)

**To reproduce**

- `sfdx force:source:convert -d deployment`
- `sfdx force:mdapi:deploy -d deployment --testlevel RunSpecifiedTests --runtests "DataModelTest,DataStoreTest,EvaluationReasonTest,EvaluatorOperatorTest,EvaluatorTest,EventProcessorTest,EventRESTTest,EventSinkTest,EventTest,LDClientTest,LDUserTest,LDValueTest,SemanticVersionTest"`

**Expected behavior**
All code should have 75% plus code coverage and the SDK should be deploy ready

**SDK version**
apex-server-sdk-1.1.0

**Comment by louis-launchdarkly** [comment]
Hello @jitenderpadda, thank you for reaching out. It seems there are two separate questions here - why the deployment is not working, and this Apex SDK's code coverage.

This is a bit weird because when I install only the classes from this SDK to a brand new development org (i.e. no other Apex that affects the calculation), it has 80% coverage.
<img width="352" alt="Screen Shot 2022-02-11 at 2 38 57 PM" src="https://user-images.githubusercontent.com/91093020/153680640-d336c830-854e-4634-ae0f-960069389fe9.png">

And based on [some discussion](https://salesforce.stackexchange.com/questions/198603/why-salesforce-allow-us-to-deploy-class-with-0-percent-code-coverage) from the Salesforce StackExchange forum, if your other Apex code already has 75% coverage or more, the LaunchDarkly SDK will not bring down the average to the point that it blocks deployment.

Also, can you provide more information on how do you come up with the reproduction commands? I try running it against a dev org, but I just get 0% for every class, which is different from what you get.
<img width="565" alt="Screen Shot 2022-02-11 at 2 47 35 PM" src="https://user-images.githubusercontent.com/91093020/153681096-e894d249-2d1f-4a18-a6ee-2740618c6e88.png">

**Comment by jitenderpadda** [comment]
@louis-launchdarkly Thanks for getting back to me. I updated the command in the question - I have namespaced the classes with LD_ so had to remove that.

On the code coverage issue, I am only deploying the sdk and running only test classes for the SDK, so it is probably bringing down the overall org code coverage. Is that correct?

**Comment by louis-launchdarkly** [comment]
Hello @jitenderpadda, while there is some clean-up we want to do and I think it is reasonable to increase coverage, at this point I cannot provide a timeframe yet. I will mark this as an enhancement and track it.

In terms of installing, I recommend you file a Support ticket with our Support team. They are more familiar with the SDK setup process and may have other suggestions for you.

_Filed Internally as 143027._
